- name: Build and Push Docker image
  uses: docker/build-push-action@v5
  with:
    context: ./09_huggingface-fastapi
    file: ./09_huggingface-fastapi/Dockerfile
    push: true
    tags: ${{ secrets.DOCKER_USERNAME }}/huggingface-fastapi:latest
