name: Test Docker Hub Push
on: workflow_dispatch

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build tiny test image
        run: |
          cat > Dockerfile <<'EOF'
          FROM busybox
          CMD echo "token ok"
          EOF
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/token-test:gh-${{ github.run_id }} .

      - name: Push test image
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/token-test:gh-${{ github.run_id }}

      # Optional: delete the tag afterward to keep your Hub clean
      - name: Cleanup tag on Docker Hub
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
          TAG: gh-${{ github.run_id }}
        run: |
          REPO="token-test"
          # Delete tag via Docker Hub API
          curl -fsSL -u "$USERNAME:$TOKEN" -X DELETE \
            "https://hub.docker.com/v2/repositories/$USERNAME/$REPO/tags/$TAG/" || true
